name: lqr

dependencies:
    - python==3.6.3
    - pip:
      - ray==0.7.2
      - tensorflow==1.13.1
      - gym==0.10.8
      - lz4==2.1.1
      - opencv-python==3.4.3.18
      - redis==2.10.6
      - psutil
      - matplotlib
      - pandas
